---
name: Trigger download files
    
on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in test
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: caffreyu/test
          event-type: test-workflow
          client-payload: '{"ref" : "${{ github.ref }}"}'
